services:
  backend:
    build:
      context: ./src
      dockerfile: deployment/Dockerfile.api
    container_name: credit-risk-backend
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app
      - ./logs:/app/logs
    environment:
      - MODEL_VERSION=v1
    command: uvicorn deployment.api:app --host 0.0.0.0 --port 8000

  frontend:
    build:
      context: ./src
      dockerfile: frontend/Dockerfile.frontend
    container_name: credit-risk-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - ./src:/app
